### ISSUE TITLE
 Unable to detect IP address from 

### ISSUE THREAD

**Issue by matheusccarvalho** [zidansec/CloudPeler#5]
Hello, this error is showing up for any websites.

 - Unable to detect IP address from 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/58345779/181071831-4db1e33e-973d-4548-a1f9-a59ac601b678.png">

**Comment by FALL1N1** [comment]
that's because crimeflare.herokuapp.com is down, don't expect it to get fixed

**Comment by jcn50** [comment]
> that's because crimeflare.herokuapp.com is down, don't expect it to get fixed

Why shouldn't we expect to get it fixed?...

**Comment by FALL1N1** [comment]
> > that's because crimeflare.herokuapp.com is down, don't expect it to get fixed
> 
> @FALL1N1 Why shouldn't we expect to get it fixed?...

because the way it works is stupid and useless, it just obtains information from random websites like "dnstrails" and provides you with the results (note that you must have accounts with them and pay a fee)

it does not do any sort of "hacking" whatsoever and if the website you want to take down has no "SPF", "MX" or any other DNS records revealing their IP - you will never obtain the host unless you have a friend working at CloudFlare with high access

**Comment by zidansec** [comment]
> > > itu karena crimeflare.herokuapp.com sedang down, jangan harap bisa diperbaiki
> > 
> > 
> > @FALL1N1Mengapa kita tidak berharap untuk memperbaikinya?...
> 
> karena cara kerjanya bodoh dan tidak berguna, itu hanya memperoleh informasi dari situs web acak seperti "dnstrails" dan memberi Anda hasilnya (perhatikan bahwa Anda harus memiliki akun dengan mereka dan membayar biaya)
> 
> itu tidak melakukan "peretasan" apa pun dan jika situs web yang ingin Anda hapus tidak memiliki "SPF", "MX" atau catatan DNS lainnya yang mengungkapkan IP mereka - Anda tidak akan pernah mendapatkan host kecuali Anda memiliki teman yang bekerja di CloudFlare dengan akses tinggi

Yes, it works with CloudFlare database pools circa 2018. And it allows working on legacy sites that still rely on Cloudflare as WAF. But no updates for new sites using cloudflare. So it can be concluded that this tool only works on sites that have been around for a long time. The database we use is the same as the database at crimeflare.org which existed several years ago. And now there are no more updates regarding the database. Although I have a manual way to see the IP behind cloudflare but to realize it is quite difficult.

**Comment by zidansec** [comment]
Of course, I already said that this tool does not guarantee 100% that it can see the real IP of cloudflare protected websites. The tool that guarantees is your own ability not with tools alone. Research manually or with a tool is needed to find the Original IP of the cloudflare waf.

**Comment by d4rks0ul555** [comment]
if there is no misconfiguration and all old ip moved to cloudflare server and even you knew the real ip but already moved to cloudflare server it's gonna be useless

**Comment by KaKi87** [comment]
@zidansec Where can that database be found ?

If I can download it, then I would create an app that works offline, also I'm thinking about creating a DNS server based on it.

Thanks

**Comment by zidansec** [comment]
This tool is back in operation, but need to know. This tool is not 100% accurate, because as I explained. The way this tool works takes advantage of Cloudflare's leaked database in 2018. New API [https://crimeflare.zidansec.com](https://crimeflare.zidansec.com)

**Comment by KaKi87** [comment]
> Cloudflare's leaked database in 2018

Where can we find that ? Thanks
