### ISSUE TITLE
It goes to 100% on any given website and does nothing after that

### ISSUE THREAD

**Issue by miladf2** [zidansec/CloudPeler#6]
Scanning: exemple.com
############################################################################################]

**Comment by huntergins4376** [comment]
Same for me i can see they dont plan on fixing it either

**Comment by spmedia** [comment]
Its pretty much a skiddie app. It does not work any longer because where it pulls info from (https://crimeflare.herokuapp.com/) is down.

**Comment by zidansec** [comment]
That's because this project has been terminated. It won't work anymore.
