### ISSUE TITLE
Currently CloudPeler or CrimeFlare are no longer working!

### ISSUE THREAD

**Issue by zidansec** [zidansec/CloudPeler#9]
Currently CloudPeler or CrimeFlare are no longer working, because we don't have hosting for the API running behind these tools. So wait until later, it will be operational again!

**Comment by zidansec** [comment]
This tool is back in operation, but need to know. This tool is not 100% accurate, because as I explained. The way this tool works takes advantage of Cloudflare's leaked database in 2018. New API [https://crimeflare.zidansec.com](https://crimeflare.zidansec.com)

**Comment by d7e7r7** [comment]
> This tool is back in operation, but need to know. This tool is not 100% accurate, because as I explained. The way this tool works takes advantage of Cloudflare's leaked database in 2018. New API https://crimeflare.zidansec.com

This link just says "There's nothing here, yet."
